# -*- coding: utf-8 -*-
"""Homes in Ames Iowa ERD - Alex Hill.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t-lhzk2nbY32RmYfQe048at86ppWIC8p
"""

import pandas as pd
df = pd.read_csv('https://www.dropbox.com/scl/fi/vi8xx6yz7jl6lkrvwkq3z/AmesHousing.csv?rlkey=rpj70q7o5zew27hu3qpeht4ra&st=bemuxmhf&dl=1')

df.head(1000)

df.info()

"""## 1. Do larger homes sell for more?"""

def central_tendency(a_value):
  mean = df[a_value].mean()
  median = df[a_value].median()
  mode = df[a_value].mode()
  print("Central tendency:")
  print(f"{mean:.3f}",' ', f"{median:.2f}",' ', mode)

central_tendency('Gr Liv Area')

central_tendency('SalePrice')

import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import linregress


sns.lmplot(x= 'Gr Liv Area', y='SalePrice', data=df)
plt.title('Quantity vs Sales Price')
plt.show()

slope, intercept, r_value, p_value, std_err = linregress(x=df['Gr Liv Area'], y=df['SalePrice'])

print(f"Regression equation: Profit = {intercept:.2f} + {slope:.2f} * Gr Liv Area")
print(f"R-value: {r_value:.2f}")
print(f"R-squared: {r_value**2:.4f}")
print(f"P-value: {p_value:.2f}")

"""### Findings
I found a relatively strong relationship between house size and sale price. While they're not perfectly correlated, the connection is extremely close.

## 2. Are homes in some neighborhood regions more expensive than others on average?
"""

df['Neighborhood'].unique()

df['Region'] = 'Other'
df.loc[df['Neighborhood'].isin(['NWAmes', 'Gilbert', 'Veenker','SawyerW','Timber','Mitchel','Blueste']), 'Region'] = 'Northwest Ames'
df.loc[df['Neighborhood'].isin(['NridgHt', 'NoRidge', 'StoneBr', 'Somerst', 'ClearCr', 'Greens']),'Region'] = 'Northeast Ames'
df.loc[df['Neighborhood'].isin(['OldTown','SWISU', 'BrkSide', 'Crawfor', 'CollgCr']),'Region'] = 'Central Ames/University Area'
df.loc[df['Neighborhood'].isin(['Blmngtn', 'Sawyer','Edwards','NAmes']),'Region'] = 'Southwest Ames'
df.loc[df['Neighborhood'].isin(['BrDale', 'NPkVill', 'IDOTRR', 'MeadowV', 'GrnHill', 'Landmrk']),'Region'] = 'Southeast Ames/Industrial Edge'

df.groupby('Region')['SalePrice'].sum()

round(df.groupby('Region')['SalePrice'].mean(), 2)

sns.barplot(x = 'Region', y = 'SalePrice', data=df)
plt.xticks(rotation=60)

"""### Analysis
Upon further analysis we can see that the region does tend to relate to the price of homes. For example Northeast Ames was on average $137720.75 more than the central region. Its also important to note that homes in the Northeast cost the most on average.

## 3. Describe the association between the quality of exterior materials and price for single family detached homes.
"""

df['Bldg Type'].unique()

df['Exter Qual'].unique()

df['Bldg Type'].value_counts()

"""#### A-NOVA/Tukey/Graphs"""

import pandas as pd
from scipy import stats

groups = df['Exter Qual'].unique()
group_labels = []
for g in groups:
  group_labels.append(df[df['Exter Qual'] == g]['SalePrice'])
f, p =  stats.f_oneway(*group_labels)

print('F: ' + str(round(f, 4)))
print('p: ' + str(round(p, 4)))

from statsmodels.stats.multicomp import pairwise_tukeyhsd

tukey = pairwise_tukeyhsd(endog=df['SalePrice'],
                          groups=df['Exter Qual'],
                          alpha=0.05)

print(tukey)

import matplotlib.pyplot as plt

sns.barplot(x = 'Exter Qual', y = 'SalePrice', hue = 'Bldg Type', data = df)

plt.title('Sale Price by Exterior Quality and Building Type')
plt.xticks(rotation=30)
plt.show()

"""### Analysis
There seems to be a strong positve relation with exterior quality and single family homes.

## 4. Describe the association between the year the home was built and the sale price.
"""

df.groupby('Year Built')['SalePrice'].sum()

from scipy.stats import linregress


sns.lmplot(x= 'Year Built', y='SalePrice', data=df)
plt.title('Year Built vs Sale Price')
plt.show()

slope, intercept, r_value, p_value, std_err = linregress(x=df['Year Built'], y=df['SalePrice'])

print(f"Regression equation: Profit = {intercept:.2f} + {slope:.2f} * Year Built")
print(f"R-value: {r_value:.2f}")
print(f"R-squared: {r_value**2:.4f}")
print(f"P-value: {p_value:.2f}")

"""### Analysis
Heres what I found, there is a slight corrilation between the year the house was built and the sale price of it. Each year the value of the the house increases roughly $1475.

## 5. Are garage types associated with price differences?
"""

df['Garage Type'].unique()

df['Garage Type'] = df['Garage Type'].fillna("No Garage")

groups = df['Garage Type'].unique()
group_labels = []
for g in groups:
  group_labels.append(df[df['Garage Type'] == g]['SalePrice'])
f, p =  stats.f_oneway(*group_labels)

print('F: ' + str(round(f, 4)))
print('p: ' + str(round(p, 4)))

tukey = pairwise_tukeyhsd(endog=df['SalePrice'],
                          groups=df['Garage Type'],
                          alpha=0.05)

print(tukey)

"""#### Analysis
I found that garage type is related to sale price, but not all garage types show the same relationship. Built-in and attached garages are consistently associated with higher home prices. In contrast, detached garages, carports, and basement
garages show weaker or less consistent relationships with price.

## 6. Do homes with finished basements sell for more than homes with unfinished basements (don't account for homes without basements)?
"""

df['BsmtFin Type 1'].value_counts()

df['BsmtFin Type 1'] = df['BsmtFin Type 1'].fillna("No Basement")

groups_df = df[df['BsmtFin Type 1'] != 'No Basement']
categories = groups_df['BsmtFin Type 1'].unique()
colors = ['royalblue' if cat == 'Unf' else 'grey' for cat in categories]

sns.barplot(x = 'BsmtFin Type 1', y = 'SalePrice', data = groups_df, palette=colors)


plt.title('Sale Price by Exterior Quality and Building Type')
plt.xticks(rotation=30)
plt.show()

df['basement_type'] = 'No Basement'
df.loc[df['BsmtFin Type 1'].isin(['GLQ', 'BLQ', 'Rec', 'ALQ', 'LwQ']), 'basement_type'] = 'Finished'
df.loc[df['BsmtFin Type 1']== 'Unf', 'basement_type'] = 'Unfinished'

df['basement_type'].value_counts()

Fin = df[df['basement_type'] == 'Finished']
Unf = df[df['basement_type'] == 'Unfinished']

t, p = stats.ttest_ind(Fin['SalePrice'], Unf['SalePrice'])

print("t: " + str(round(t, 2)))
print("p: " + str(round(p, 5)))

"""#### Analysis
There is statistically significant evidence that the average price differs between homes with unfinished and finished basements.  With finished basements selling for more on average.

## 7. Describe the association between overall quality rating and sale price.
"""

df['Overall Qual'].unique()

df['Overall Qual'].value_counts()

groups = df['Overall Qual'].unique()
group_labels = []
for g in groups:
  group_labels.append(df[df['Overall Qual'] == g]['SalePrice'])
f, p =  stats.f_oneway(*group_labels)

print('F: ' + str(round(f, 4)))
print('p: ' + str(round(p, 4)))

tukey = pairwise_tukeyhsd(endog=df['SalePrice'],
                          groups=df['Overall Qual'],
                          alpha=0.05)

print(tukey)

sns.lmplot(x= 'Overall Qual', y='SalePrice', data=df)
plt.title('Overall Quantity vs Sales Price')
plt.show()

slope, intercept, r_value, p_value, std_err = linregress(x=df['Overall Qual'], y=df['SalePrice'])

print(f"Regression equation: Profit = {intercept:.2f} + {slope:.2f} * Overall Qual")
print(f"R-value: {r_value:.4f}")
print(f"R-squared: {r_value**2:.4f}")
print(f"P-value: {p_value:.2f}")

"""#### Analysis
There is a strong positive relationship between the quality rating and sales price. On average, the price increases by approximately $45,251 for each 1-point increase in the overall quality rating.

## 8. Describe the association between house type and neighborhood regions.
"""

df.head()

crosstab = pd.crosstab(index = df['Bldg Type'], columns = df['Region'], margins = False)
plt.title('Observed Counts of Building type and Region')

sns.heatmap(crosstab, annot=True, fmt='d', cmap='coolwarm')

plt.show()

import numpy as np
from scipy.stats import chi2_contingency

crosstab = pd.crosstab(index = df['Bldg Type'], columns = df['Region'], margins = False)

x, p, dof, expected_values = chi2_contingency(crosstab)

expected_values_df = pd.DataFrame(np.rint(expected_values).astype('int64'), columns=crosstab.columns, index = crosstab.index )

sns.heatmap(expected_values_df, annot=True,  fmt='d', cmap='coolwarm')

plt.title('Expected Values of Bulding Type and Region')

plt.show()

from scipy.stats import chi2_contingency

crosstab = pd.crosstab(index = df['Bldg Type'], columns = df['Region'], margins = True)


x, p, dof, expected_values = chi2_contingency(crosstab)

print(f"p-value: {p:.4f}")

"""#### Analysis
There is a statistically significant relationship between building type and neighborhood region—certain building types are more common in specific regions. This is particularly evident when comparing the central and southeast regions. We expected building types other than single-family homes to be more prevalent in the central region and less common in the southeast region. However, the data revealed the opposite pattern.
"""